[package]
name = "nft_staking"
version = "1.0.0"
authors = []

[addresses]
admin_addr='0xbeef'
source_addr='0xcafe'
nft_staking_addr='0xc3bb8488ab1a5815a9d543d7e41b0e0df46a7396f89b22821f07a4362f75ddc5'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnt"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]